server {
    listen 80;
    
    # Set the root directory for the Nginx server
    root /usr/share/nginx/html;
    index index.html;

    # Route all requests to index.html to support SPA routing (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}